# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: GitHub-Based Impact Analysis

on:
  workflow_dispatch:

jobs:
  impact-analysis:
    runs-on: ubuntu-latest

    env:
      SOURCE_BRANCH: main
      TARGET_BRANCH: feature-xyz
      ZIP_FILE: source_code.zip
      DIFF_FILE: code_changes.diff
      OUTPUT_JSON: impact_output.json
      SERVER_PORT: 8890

    steps:

    # Step 1: Checkout repo and fetch all branches
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for full diff

    # Step 2: Start Impact Analysis API server
    - name: Start Impact Analysis Server
      run: |
        docker-compose up -d
        sleep 10

    # Step 3: Checkout source branch and zip contents
    - name: Zip Source Branch
      run: |
        git checkout $SOURCE_BRANCH
        git clean -fdx
        zip -r $ZIP_FILE . -x ".git/*"

    # Step 4: Send ZIP555bb to Endpoint 1
    - name: Send ZIP to Endpoint 1
      run: |
        curl -X POST http://localhost:$SERVER_PORT/upload-zip \
          -H "Content-Type: multipart/form-data" \
          -F "file=@$ZIP_FILE"

    # Step 5: Checkout target branch and generate diff
    - name: Generate Diff File
      run: |
        git checkout $TARGET_BRANCH
        git fetch origin $SOURCE_BRANCH
        git diff origin/$SOURCE_BRANCH...HEAD > $DIFF_FILE

    # Step 6: Send diff file to Endpoint 2
    - name: Send Diff to Endpoint 2
      run: |
        curl -X POST http://localhost:$SERVER_PORT/upload-diff \
          -H "Content-Type: multipart/form-data" \
          -F "file=@$DIFF_FILE" \
          -o $OUTPUT_JSON

    # Step 7: Upload output JSON as artifact
    - name: Upload Impact Output
      uses: actions/upload-artifact@v4
      with:
        name: impact_output
        path: ${{ env.OUTPUT_JSON }}
